import Link from "next/link";
import type { CampaignStatus } from "@/lib/db/types";

export type CampaignLibraryItem = { id: string; name: string; status: CampaignStatus; error_message: string | null; processing_stage: string | null; created_at: string; updated_at: string; entityCount: number };

export const campaignStatusLabels: Record<CampaignStatus, string> = { uploaded: "Ready to import", extracting_pages: "Importing campaign", extracting_candidates: "Finding entries", reconciling: "Organizing entries", persisting: "Preparing wiki", complete: "Ready", failed: "Import failed" };

function statusClass(status: CampaignStatus) { if (status === "failed") return "border-red-200 bg-red-50 text-red-800"; if (status === "complete") return "border-emerald-200 bg-emerald-50 text-emerald-800"; return "border-amber-200 bg-amber-50 text-amber-900"; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value)); }

export function CampaignLibrary({ campaigns, loadFailed, heading = "Your campaigns", description }: { campaigns: CampaignLibraryItem[]; loadFailed: boolean; heading?: string; description?: string }) {
  return <section id="campaigns" aria-labelledby="campaign-library-heading">
    <div className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--line)] pb-5"><div><p className="eyebrow">Campaign library</p><h2 id="campaign-library-heading" className="mt-2 font-serif text-3xl font-semibold tracking-tight sm:text-4xl">{heading}</h2>{description ? <p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">{description}</p> : null}</div>{!loadFailed ? <p className="text-sm text-[var(--muted)]">{campaigns.length} {campaigns.length === 1 ? "campaign" : "campaigns"}</p> : null}</div>
    {loadFailed ? <p role="alert" className="mt-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">Campaigns could not be loaded. Check the server configuration and try again.</p>
      : campaigns.length === 0 ? <div className="mt-6 rounded-xl border border-dashed border-[var(--line)] bg-white/45 p-7 sm:p-9"><h3 className="font-serif text-2xl font-semibold">Begin with your campaign material.</h3><p className="mt-2 max-w-xl leading-7 text-[var(--muted)]">Import a text-based PDF to create a source-backed home for its people, places, and connections.</p><Link className="button-primary mt-6 inline-flex" href="/import">Import a campaign</Link></div>
      : <ul className="mt-6 grid gap-4 lg:grid-cols-2">{campaigns.map((campaign) => { const complete = campaign.status === "complete"; const failed = campaign.status === "failed"; const href = complete ? `/campaigns/${campaign.id}` : `/campaigns/${campaign.id}/processing`; const action = complete ? "Open campaign" : failed ? "View import details" : "View progress"; return <li key={campaign.id}><Link className="group flex h-full flex-col rounded-xl border border-[var(--line)] bg-white/65 p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[var(--accent)] hover:shadow-md focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]" href={href}><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="font-serif text-2xl font-semibold leading-tight group-hover:text-[var(--accent)]">{campaign.name}</h3><span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${statusClass(campaign.status)}`}>{campaignStatusLabels[campaign.status]}</span></div><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{complete ? `${campaign.entityCount} ${campaign.entityCount === 1 ? "wiki entry" : "wiki entries"}` : failed ? "The import could not be completed. Review the import details to try again." : campaign.processing_stage ?? "Your campaign is being prepared."}</p><div className="mt-auto flex items-center justify-between gap-4 pt-6 text-sm"><time className="text-[var(--muted)]" dateTime={campaign.updated_at}>Updated {formatDate(campaign.updated_at)}</time><span className="font-semibold text-[var(--accent)]">{action} <span aria-hidden="true">→</span></span></div></Link></li>; })}</ul>}
  </section>;
}
