import { loadEnvConfig } from "@next/env";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { request as httpRequest } from "node:http";
import { z } from "zod";
import { buildInventoryInput, EXTRACTION_INVENTORY_SYSTEM_PROMPT } from "../lib/ai/prompts";
import { validateExtractionInventory } from "../lib/ai/source-validation";
import { resolveAIProviderConfig } from "../lib/env";
import { categoryInventoryPrompt, categoryInventorySchema } from "./ollama-inventory-category";
import { boundedEvidenceSchema, namesOnlySchema, repetitionMetrics } from "./ollama-inventory-pathology";
import type { DocumentPage, PageChunk } from "../lib/pdf/types";

loadEnvConfig(process.cwd());
const HASH = "9252d865dacb1e30271bddc9308343d9b5c037d9298a89ee5a41404a5c35290b"; const MODEL = "qwen3.5:9b"; const DIR = new URL("../artifacts/ollama-inventory-pathology/", import.meta.url); const PATH = new URL("result.json", DIR);
const category = "deity" as const;
const hash = (pages: PageChunk["pages"]) => createHash("sha256").update(pages.map((p) => `<campaign-page number="${p.pageNumber}">\n${p.text}\n</campaign-page>`).join("\n\n")).digest("hex");
async function stream(endpoint: string, body: string, headers: Record<string,string>, started: number) { const response = await fetch(endpoint, { method: "POST", headers, body, signal: AbortSignal.timeout(900000) }); if (!response.ok || !response.body) throw new Error(`HTTP_${response.status}`); const reader=response.body.getReader(); const decoder=new TextDecoder(); let buffer="", content="", firstByte:number|null=null, usage: unknown=null, done=false; const consume=(event:string)=>{ const data=event.split(/\r?\n/).filter((x)=>x.startsWith("data:")).map((x)=>x.slice(5).trimStart()).join("\n"); if(!data)return; if(data==="[DONE]"){done=true;return;} const x=JSON.parse(data) as {choices?:Array<{delta?:{content?:string}}>;usage?:unknown}; content+=x.choices?.[0]?.delta?.content??""; usage??=x.usage??null; }; while(!done){const next=await reader.read();if(next.done)break;firstByte??=Math.round(performance.now()-started);buffer+=decoder.decode(next.value,{stream:true});let boundary;while((boundary=buffer.search(/\r?\n\r?\n/))!==-1){const e=buffer.slice(0,boundary);const d=buffer[boundary]==="\r"?4:2;buffer=buffer.slice(boundary+d);consume(e);}} return {content,firstByteMs:firstByte,usage,done}; }
async function post(endpoint:string,body:string,headers:Record<string,string>,started:number){const u=new URL(endpoint);return new Promise<{text:string;firstByteMs:number}>((resolve,reject)=>{const req=httpRequest({protocol:u.protocol,hostname:u.hostname,port:u.port,path:u.pathname,method:"POST",headers:{...headers,"content-length":Buffer.byteLength(body).toString()}},res=>{const fb=Math.round(performance.now()-started),parts:Buffer[]=[];res.on("data",(p:Buffer)=>parts.push(p));res.on("end",()=>resolve({text:Buffer.concat(parts).toString(),firstByteMs:fb}));res.on("error",reject)});req.setTimeout(900000,()=>req.destroy(new Error("900000ms timeout")));req.on("error",reject);req.end(body)});}
function bodyFor(schema: z.ZodType, prompt: string, chunk: PageChunk) { return JSON.stringify({ model: MODEL, messages:[{role:"system",content:`${EXTRACTION_INVENTORY_SYSTEM_PROMPT}\n${prompt}\nReturn only valid JSON.`},{role:"user",content:buildInventoryInput(chunk)}],response_format:{type:"json_schema",json_schema:{name:"pathology_inventory",strict:true,schema:z.toJSONSchema(schema)}},reasoning_effort:"none",temperature:0 }); }
async function main(){if(existsSync(PATH))throw new Error("Existing pathology result; no rerun");const c=resolveAIProviderConfig(process.env,"extraction_inventory");if(c.providerId!=="local"||c.modelId!==MODEL||c.allowPersistence)throw new Error("frozen local config mismatch");const {createAdminClient}=await import("../lib/db/client");const db=createAdminClient();const doc=await db.from("documents").select("id").eq("campaign_id","d14f9875-5ebf-46c6-b07e-d65a3e65c5f4").single();if(doc.error)throw doc.error;const pagesR=await db.from("document_pages").select("page_number,text").eq("document_id",doc.data.id).order("page_number");if(pagesR.error||!pagesR.data)throw pagesR.error;const pages=[38,39,40,41].map((n):DocumentPage=>{const p=pagesR.data.find(x=>x.page_number===n);if(!p)throw new Error(`missing ${n}`);return{pageNumber:n,text:p.text}});const chunk:PageChunk={id:"chunk-3:pressure:4:1",pages,characterCount:pages.reduce((s,p)=>s+p.text.length,0)};if(hash(pages)!==HASH)throw new Error("hash mismatch");const headers={"content-type":"application/json",...(c.apiKey?{authorization:`Bearer ${c.apiKey}`}:{})};const endpoint=`${c.baseUrl}/chat/completions`;
const skipCapture=process.argv.includes("--skip-capture");const aStart=performance.now();const streamed=skipCapture?null:await stream(endpoint,bodyFor(categoryInventorySchema(category),categoryInventoryPrompt(category),chunk),headers,aStart);const aText=streamed?.content??"";let aError:string|null=skipCapture?"Call A fetch failed before streamed content was received":null;try{if(!skipCapture)validateExtractionInventory(categoryInventorySchema(category).parse(JSON.parse(aText)),pages)}catch(e){aError=e instanceof Error?e.message:String(e)};const A={contract:"current_category_inventory",valid:!aError,latencyMs:Math.round(performance.now()-aStart),firstByteMs:streamed?.firstByteMs??null,totalCharacters:aText.length,outputBytes:Buffer.byteLength(aText),usage:streamed?.usage??null,streamDone:streamed?.done??false,error:aError,repetition:repetitionMetrics(aText),firstExcerpt:aText.slice(0,8000),lastExcerpt:aText.slice(-8000)};
const runCompact=async(schema:z.ZodType,prompt:string,kind:string)=>{const started=performance.now();try{const r=await post(endpoint,bodyFor(schema,prompt,chunk),headers,started);const env=JSON.parse(r.text) as {choices?:Array<{message?:{content?:string}}>;usage?:{prompt_tokens?:number;completion_tokens?:number;total_tokens?:number}};const text=env.choices?.[0]?.message?.content??"";const parsed=schema.parse(JSON.parse(text)) as {entities:Array<{name:string}>};return{contract:kind,valid:true,latencyMs:Math.round(performance.now()-started),firstByteMs:r.firstByteMs,outputCharacters:text.length,outputBytes:Buffer.byteLength(text),usage:env.usage??null,entityCount:parsed.entities.length,duplicateNormalizedNames:parsed.entities.length-new Set(parsed.entities.map(x=>x.name.toLocaleLowerCase())).size,error:null}}catch(e){return{contract:kind,valid:false,latencyMs:Math.round(performance.now()-started),error:e instanceof Error?e.message:String(e)}}};
const B=await runCompact(namesOnlySchema,`${categoryInventoryPrompt(category)} Names only: no IDs, aliases, evidence, prose, facts, relationships, or other types.`,"names_only");const C=B.valid?await runCompact(boundedEvidenceSchema,`${categoryInventoryPrompt(category)} Return only name and one short page-numbered supporting excerpt (maximum 240 characters). No IDs, aliases, prose, facts, relationships, or other types.`,"name_plus_bounded_evidence"):null;const result={category,sourceHash:HASH,A,B,C,openAICalls:0,localGenerationCalls:(skipCapture?0:1)+1+(C?1:0),campaignWrites:0,reconciliationCalls:0,enrichmentCalls:0,checkpointWrites:0};mkdirSync(DIR,{recursive:true});writeFileSync(PATH,`${JSON.stringify(result,null,2)}\n`);console.log(JSON.stringify({A:{...A,firstExcerpt:undefined,lastExcerpt:undefined},B,C,openAICalls:0,localGenerationCalls:result.localGenerationCalls},null,2));}
main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1});
