import { loadEnvConfig } from "@next/env";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { request as httpRequest } from "node:http";
import { z } from "zod";
import { buildInventoryInput, EXTRACTION_INVENTORY_SYSTEM_PROMPT } from "../lib/ai/prompts";
import type { ExtractionInventoryOutput } from "../lib/ai/schemas";
import { validateExtractionInventory } from "../lib/ai/source-validation";
import { resolveAIProviderConfig } from "../lib/env";
import { aggregateBoundaryInventories } from "./ollama-inventory-pressure";
import { INVENTORY_CATEGORIES, categoryInventoryPrompt, categoryInventorySchema, type InventoryCategory } from "./ollama-inventory-category";
import type { DocumentPage, PageChunk } from "../lib/pdf/types";

loadEnvConfig(process.cwd());
const SOURCE_CAMPAIGN_ID = "d14f9875-5ebf-46c6-b07e-d65a3e65c5f4"; const CACHE_ID = "1ad99ac3-6cf5-4731-bf1e-4736109f0de8"; const EXPECTED_MODEL = "qwen3.5:9b"; const EXPECTED_DIGEST = "6488c96fa5faab64bb65cbd30d4289e20e6130ef535a93ef9a49f42eda893ea7"; const EXPECTED_HASH = "9252d865dacb1e30271bddc9308343d9b5c037d9298a89ee5a41404a5c35290b";
const artifactDirectory = new URL("../artifacts/ollama-inventory-category/", import.meta.url); const manifestPath = new URL("manifest.json", artifactDirectory);
const sourceHash = (pages: PageChunk["pages"]) => createHash("sha256").update(pages.map((page) => `<campaign-page number="${page.pageNumber}">\n${page.text}\n</campaign-page>`).join("\n\n")).digest("hex");

async function digest(baseUrl: string, model: string) { const r = await fetch(`${new URL(baseUrl).origin}/api/tags`); const body = await r.json() as { models?: Array<{ name?: string; digest?: string }> }; return body.models?.find((item) => item.name === model)?.digest ?? null; }
async function post(endpoint: string, body: string, headers: Record<string, string>, started: number) { const u = new URL(endpoint); return new Promise<{ status: number; text: string; firstByteMs: number }>((resolve, reject) => { const req = httpRequest({ protocol: u.protocol, hostname: u.hostname, port: u.port, path: u.pathname, method: "POST", headers: { ...headers, "content-length": Buffer.byteLength(body).toString() } }, (res) => { const firstByteMs = Math.round(performance.now() - started); const parts: Buffer[] = []; res.on("data", (part: Buffer) => parts.push(part)); res.on("end", () => resolve({ status: res.statusCode ?? 0, text: Buffer.concat(parts).toString("utf8"), firstByteMs })); res.on("error", reject); }); req.setTimeout(900000, () => req.destroy(new Error("900000ms timeout"))); req.on("error", reject); req.end(body); }); }

async function run(config: Extract<ReturnType<typeof resolveAIProviderConfig>, { providerId: "local" }>, chunk: PageChunk, category: InventoryCategory) {
  const started = performance.now(); const base = { category, status: "failed" as const, latencyMs: 0, firstByteMs: null as number | null, outputCharacters: null as number | null, outputBytes: null as number | null, usage: null as { inputTokens: number | null; outputTokens: number | null; totalTokens: number | null } | null, entityCount: null as number | null, duplicateTemporaryIds: null as number | null, incomplete: false, failure: null as string | null };
  try { const body = JSON.stringify({ model: config.modelId, messages: [{ role: "system", content: `${EXTRACTION_INVENTORY_SYSTEM_PROMPT}\n${categoryInventoryPrompt(category)}\nReturn only valid JSON matching the requested category_inventory structure.` }, { role: "user", content: buildInventoryInput(chunk) }], response_format: { type: "json_schema", json_schema: { name: `category_inventory_${category}`, strict: true, schema: z.toJSONSchema(categoryInventorySchema(category)) } }, reasoning_effort: "none", temperature: 0 }); const response = await post(`${config.baseUrl}/chat/completions`, body, { "content-type": "application/json", ...(config.apiKey ? { authorization: `Bearer ${config.apiKey}` } : {}) }, started); base.firstByteMs = response.firstByteMs; if (response.status < 200 || response.status >= 300) throw new Error(`HTTP_${response.status}`); const envelope = JSON.parse(response.text) as { choices?: Array<{ message?: { content?: string } }>; usage?: { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number } }; const content = envelope.choices?.[0]?.message?.content; if (!content) throw new Error("missing content"); base.outputCharacters = content.length; base.outputBytes = Buffer.byteLength(content); base.usage = { inputTokens: envelope.usage?.prompt_tokens ?? null, outputTokens: envelope.usage?.completion_tokens ?? null, totalTokens: envelope.usage?.total_tokens ?? null }; const raw = categoryInventorySchema(category).parse(JSON.parse(content)); const validated = validateExtractionInventory(raw, chunk.pages).inventory; const ids = validated.entities.map((entity) => entity.temporary_id); return { ...base, status: "success" as const, latencyMs: Math.round(performance.now() - started), entityCount: validated.entities.length, duplicateTemporaryIds: ids.length - new Set(ids).size, inventory: validated };
  } catch (error) { const failure = error instanceof Error ? error.message : String(error); return { ...base, latencyMs: Math.round(performance.now() - started), incomplete: /Unexpected end|Unterminated string/i.test(failure), failure }; }
}

async function main() {
  if (existsSync(manifestPath)) throw new Error("Existing category manifest found; no rerun permitted"); const config = resolveAIProviderConfig(process.env, "extraction_inventory"); if (config.providerId !== "local" || config.modelId !== EXPECTED_MODEL || config.allowPersistence || Number(process.env.LOCAL_AI_EXTRACTION_CONCURRENCY ?? "1") !== 1 || await digest(config.baseUrl, config.modelId) !== EXPECTED_DIGEST) throw new Error("Frozen local environment mismatch");
  const { createAdminClient } = await import("../lib/db/client"); const db = createAdminClient(); const doc = await db.from("documents").select("id").eq("campaign_id", SOURCE_CAMPAIGN_ID).single(); if (doc.error) throw doc.error; const [pagesResult, chunksResult] = await Promise.all([db.from("document_pages").select("page_number,text").eq("document_id", doc.data.id).order("page_number"), db.from("extraction_cache_chunks").select("chunk_id,chunk_index,page_numbers").eq("cache_run_id", CACHE_ID).order("chunk_index")]); if (pagesResult.error || chunksResult.error || !pagesResult.data || !chunksResult.data) throw pagesResult.error ?? chunksResult.error ?? new Error("source unavailable"); const stored = chunksResult.data.find((item) => item.chunk_index + 1 === 3)!; const pages = stored.page_numbers.filter((number) => number >= 38 && number <= 41).map((number): DocumentPage => { const page = pagesResult.data.find((item) => item.page_number === number); if (!page) throw new Error(`page ${number} missing`); return { pageNumber: number, text: page.text }; }); const chunk: PageChunk = { id: "chunk-3:pressure:4:1", pages, characterCount: pages.reduce((sum, page) => sum + page.text.length, 0) }; if (sourceHash(pages) !== EXPECTED_HASH) throw new Error("frozen pages 38-41 hash mismatch");
  const calls = []; for (const category of INVENTORY_CATEGORIES) { console.log(JSON.stringify({ event: "category_started", category })); const result = await run(config, chunk, category); calls.push(result); console.log(JSON.stringify({ event: "category_finished", category, status: result.status, latencyMs: result.latencyMs })); }
  const all = calls.every((call) => call.status === "success"); const union = all ? aggregateBoundaryInventories(calls.map((call) => ({ subchunkId: call.category, inventory: (call as { inventory: ExtractionInventoryOutput }).inventory }))) : null; const manifest = { status: "complete", source: { pages: [38,39,40,41], hash: EXPECTED_HASH, characterCount: chunk.characterCount }, allCategoriesValid: all, calls, union, reusablePriorQuarterArtifacts: true, openAICalls: 0, localGenerationCalls: calls.length, campaignWrites: 0, reconciliationCalls: 0, enrichmentCalls: 0, checkpointWrites: 0 }; mkdirSync(artifactDirectory, { recursive: true }); writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`); console.log(JSON.stringify({ allCategoriesValid: all, calls: calls.map((call) => ({ category: call.category, status: call.status, latencyMs: call.latencyMs, entityCount: call.entityCount, failure: call.failure })), union, openAICalls: 0, localGenerationCalls: calls.length }, null, 2));
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
